name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: []
body:

  - type: dropdown
    id: game
    attributes:
      label: Game
      description: Which game(s) template does the issue occur on? Select all that apply.
      multiple: true
      options:
        - Balloons
        - Bubbles
        - Bomb the Pirate
        - Categories
        - Dungeon Jump
        - Fishing
        - Fish Pond
        - Floor Keyboard
        - Flowers
        - Football
        - Geometrix
        - Image Chaser
        - Jewel Packer
        - Memory
        - Menu
        - Music Box
        - Obstacle Race
        - Paper Lines
        - Piano
        - Poll
        - Pong
        - Puzzle
        - Quiz
        - RoboTrax
        - Rubber Ducks
        - Scratch
        - Sensory Path
        - Slides
        - Stepstone
        - Storyteller
        - Theme Cards
        - The Three Billy Goats Gruff
        - Trails

  - type: input
    id: describe_bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please also add relevant screenshots/videos as attachment.
      placeholder: |
        1. Start balloon game..
        2. Pop a balloon..
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen.

  - type: checkboxes
    id: environment
    attributes:
      label: Production Environment
      description: Which server environment has the issue been observed on? Select all that apply.
      options:
        - label: Production (Stable)
        - label: Beta
        - label: Alpha

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      description: Which platform has the issue been observed on? Select all that apply.
      options:
        - label: Windows
        - label: Android
        - label: Tracking (ATrack)
        - label: Tracking (LiDAR)
        - label: Web

  - type: checkboxes
    id: installation_type
    attributes:
      label: Installation type
      description: Which installation type has the issue been observed on? Select all that apply.
      options:
        - label: WizeFloor (Ceiling)
        - label: WizeFloor Go
        - label: WizeFloor Ultra
        - label: WizeWall
