name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: []
assignees: []

body:

type: textarea
id: describe-bug
attributes:
label: Describe the bug
description: A clear and concise description of what the bug is.
placeholder: Describe what happened.
validations:
required: true

type: textarea
id: reproduce
attributes:
label: To Reproduce
description: Steps to reproduce the behavior.
placeholder: |
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error
validations:
required: true

type: textarea
id: expected-behavior
attributes:
label: Expected behavior
description: A clear and concise description of what you expected to happen.
placeholder: Describe what you expected to happen.

type: textarea
id: screenshots
attributes:
label: Screenshots
description: If applicable, add screenshots to help explain the problem.

type: dropdown
id: game
attributes:
label: Game
description: Which game template does the issue occur on? Select all that apply.
multiple: true
options:
- Balloons
- Bubbles
- Bomb the Pirate
- Categories
- Dungeon Jump
- Fishing
- Fish Pond
- Floor Keyboard
- Flowers
- Football
- Geometrix
- Image Chaser
- Jewel Packer
- Memory
- Music Box
- Obstacle Race
- Paper Lines
- Piano
- Poll
- Pong
- Puzzle
- Quiz
- RoboTrax
- Rubber Ducks
- Scratch
- Sensory Path
- Slides
- Stepstone
- Storyteller
- Theme Cards
- The Three Billy Goats Gruff
- Trails
validations:
required: true

type: textarea
id: applies-to
attributes:
label: Applies to
description: Which devices, platforms, or modes has the bug been observed on? E.g. "Windows application".
placeholder: e.g. Windows application, Chrome, iPad, etc.
